
export enum TileType {
  EMPTY = 'EMPTY',
  ROAD = 'ROAD',
  // RESIDENCIAL
  RESIDENTIAL_TRAILER = 'RESIDENTIAL_TRAILER',
  RESIDENTIAL_TINY = 'RESIDENTIAL_TINY',
  RESIDENTIAL = 'RESIDENTIAL',
  RESIDENTIAL_MODULAR = 'RESIDENTIAL_MODULAR',
  RESIDENTIAL_SUBURB = 'RESIDENTIAL_SUBURB',
  RESIDENTIAL_STUDENT = 'RESIDENTIAL_STUDENT',
  RESIDENTIAL_APARTMENTS = 'RESIDENTIAL_APARTMENTS',
  RESIDENTIAL_GATED = 'RESIDENTIAL_GATED',
  RESIDENTIAL_HIGH = 'RESIDENTIAL_HIGH',
  RESIDENTIAL_ECO = 'RESIDENTIAL_ECO',
  RESIDENTIAL_LUXURY = 'RESIDENTIAL_LUXURY',
  RESIDENTIAL_PENTHOUSE = 'RESIDENTIAL_PENTHOUSE',
  RESIDENTIAL_ARCOLOGY = 'RESIDENTIAL_ARCOLOGY',

  // TRABAJO (COMERCIAL)
  COMMERCIAL_STALL = 'COMMERCIAL_STALL',
  COMMERCIAL_FASTFOOD = 'COMMERCIAL_FASTFOOD',
  COMMERCIAL = 'COMMERCIAL',
  COMMERCIAL_OFFICE_SMALL = 'COMMERCIAL_OFFICE_SMALL',
  COMMERCIAL_CINEMA = 'COMMERCIAL_CINEMA',
  COMMERCIAL_MALL = 'COMMERCIAL_MALL',
  COMMERCIAL_HOTEL = 'COMMERCIAL_HOTEL',
  OFFICE_TOWER = 'OFFICE_TOWER',
  COMMERCIAL_HIGH = 'COMMERCIAL_HIGH',
  TECH_CAMPUS = 'TECH_CAMPUS',
  MEGA_CASINO = 'MEGA_CASINO',

  // TRABAJO (INDUSTRIAL)
  FARM = 'FARM',
  INDUSTRIAL_WORKSHOP = 'INDUSTRIAL_WORKSHOP',
  INDUSTRIAL_WAREHOUSE = 'INDUSTRIAL_WAREHOUSE',
  INDUSTRIAL = 'INDUSTRIAL',
  INDUSTRIAL_MINE = 'INDUSTRIAL_MINE',
  INDUSTRIAL_HIGH = 'INDUSTRIAL_HIGH',
  INDUSTRIAL_CHEMICAL = 'INDUSTRIAL_CHEMICAL',
  BIO_TECH_LAB = 'BIO_TECH_LAB',
  AUTOMATED_FACTORY = 'AUTOMATED_FACTORY',
  INDUSTRIAL_DATA_CENTER = 'INDUSTRIAL_DATA_CENTER',
  AEROSPACE_HANGAR = 'AEROSPACE_HANGAR',

  // ENERGÍA
  POWER_WIND = 'POWER_WIND',
  POWER_BIOMASS = 'POWER_BIOMASS',
  POWER_PLANT = 'POWER_PLANT',
  POWER_SOLAR = 'POWER_SOLAR',
  POWER_GEOTHERMAL = 'POWER_GEOTHERMAL',
  POWER_PLANT_NUCLEAR = 'POWER_PLANT_NUCLEAR',
  POWER_FUSION = 'POWER_FUSION',

  // AGUA
  WATER_PUMP = 'WATER_PUMP',
  WATER_TOWER = 'WATER_TOWER',
  WATER_TREATMENT = 'WATER_TREATMENT',
  DESALINATION_PLANT = 'DESALINATION_PLANT',

  // SERVICIOS PÚBLICOS
  POLICE_POST = 'POLICE_POST',
  POLICE = 'POLICE',
  POLICE_HQ = 'POLICE_HQ',
  FIRE_POST = 'FIRE_POST',
  FIRE_STATION = 'FIRE_STATION',
  FIRE_HQ = 'FIRE_HQ',
  FIRST_AID = 'FIRST_AID',
  HOSPITAL_CLINIC = 'HOSPITAL_CLINIC',
  HOSPITAL = 'HOSPITAL',
  MEGA_HOSPITAL = 'MEGA_HOSPITAL',
  RECYCLING = 'RECYCLING',

  // EDUCACIÓN Y CULTURA
  SCHOOL = 'SCHOOL',
  LIBRARY = 'LIBRARY',
  HIGH_SCHOOL = 'HIGH_SCHOOL',
  UNIVERSITY = 'UNIVERSITY',
  RESEARCH_LAB = 'RESEARCH_LAB',
  MUSEUM = 'MUSEUM',
  ART_GALLERY = 'ART_GALLERY',
  CULTURE_STATUE = 'CULTURE_STATUE',
  CULTURE_OPERA = 'CULTURE_OPERA',
  CULTURE_ZOO = 'CULTURE_ZOO',

  // RECREACIÓN
  PARK_SMALL = 'PARK_SMALL',
  LEISURE_SKATEPARK = 'LEISURE_SKATEPARK',
  DOG_PARK = 'DOG_PARK',
  LEISURE_POOL = 'LEISURE_POOL',
  PARK_LARGE = 'PARK_LARGE',
  LEISURE_BOTANICAL = 'LEISURE_BOTANICAL',
  STADIUM = 'STADIUM',
  THEME_PARK = 'THEME_PARK',
  VR_PLAZA = 'VR_PLAZA',

  // INFRAESTRUCTURA
  TRANSPORT_BUS = 'TRANSPORT_BUS',
  SUBWAY = 'SUBWAY',
  AIRPORT = 'AIRPORT',
  TRANSPORT_HELIPORT = 'TRANSPORT_HELIPORT',
  MAGLEV_STATION = 'MAGLEV_STATION',
  SPACE_PORT = 'SPACE_PORT'
}

export interface CityStats {
  money: number;
  population: number;
  jobs: number;
  happiness: number;
  health: number;
  education: number;
  crime: number;
  pollution: number;
  powerCapacity: number;
  powerUsage: number;
  waterCapacity: number;
  waterUsage: number;
  day: number;
  demandR: number;
  demandC: number;
  demandI: number;
  level: number;
  employed: number;
  workforce: number;
}

export interface AdvisorMessage {
  text: string;
  sender: 'ADVISOR' | 'SYSTEM';
  timestamp: number;
}
