
export enum TileType {
  EMPTY = 'EMPTY',
  ROAD = 'ROAD',
  // RESIDENCIAL
  RESIDENTIAL_TINY = 'RESIDENTIAL_TINY',
  RESIDENTIAL = 'RESIDENTIAL',
  RESIDENTIAL_SUBURB = 'RESIDENTIAL_SUBURB',
  RESIDENTIAL_APARTMENTS = 'RESIDENTIAL_APARTMENTS',
  RESIDENTIAL_HIGH = 'RESIDENTIAL_HIGH',
  RESIDENTIAL_LUXURY = 'RESIDENTIAL_LUXURY',
  RESIDENTIAL_ARCOLOGY = 'RESIDENTIAL_ARCOLOGY',

  // COMERCIAL
  COMMERCIAL_STALL = 'COMMERCIAL_STALL',
  COMMERCIAL = 'COMMERCIAL',
  COMMERCIAL_MALL = 'COMMERCIAL_MALL',
  COMMERCIAL_HIGH = 'COMMERCIAL_HIGH',
  OFFICE_TOWER = 'OFFICE_TOWER',
  TECH_CAMPUS = 'TECH_CAMPUS',
  MEGA_CASINO = 'MEGA_CASINO',

  // INDUSTRIAL
  FARM = 'FARM',
  INDUSTRIAL_WORKSHOP = 'INDUSTRIAL_WORKSHOP',
  INDUSTRIAL = 'INDUSTRIAL',
  INDUSTRIAL_HIGH = 'INDUSTRIAL_HIGH',
  BIO_TECH_LAB = 'BIO_TECH_LAB',
  AUTOMATED_FACTORY = 'AUTOMATED_FACTORY',
  AEROSPACE_HANGAR = 'AEROSPACE_HANGAR',

  // ENERGÍA
  POWER_PLANT = 'POWER_PLANT',
  POWER_SOLAR = 'POWER_SOLAR',
  POWER_WIND = 'POWER_WIND',
  POWER_PLANT_NUCLEAR = 'POWER_PLANT_NUCLEAR',
  POWER_FUSION = 'POWER_FUSION',

  // AGUA
  WATER_TOWER = 'WATER_TOWER',
  WATER_TREATMENT = 'WATER_TREATMENT',
  DESALINATION_PLANT = 'DESALINATION_PLANT',

  // SERVICIOS PÚBLICOS
  POLICE = 'POLICE',
  POLICE_HQ = 'POLICE_HQ',
  FIRE_STATION = 'FIRE_STATION',
  FIRE_HQ = 'FIRE_HQ',
  HOSPITAL_CLINIC = 'HOSPITAL_CLINIC',
  HOSPITAL = 'HOSPITAL',
  MEGA_HOSPITAL = 'MEGA_HOSPITAL',

  // EDUCACIÓN Y CULTURA
  SCHOOL = 'SCHOOL',
  LIBRARY = 'LIBRARY',
  HIGH_SCHOOL = 'HIGH_SCHOOL',
  UNIVERSITY = 'UNIVERSITY',
  RESEARCH_LAB = 'RESEARCH_LAB',
  MUSEUM = 'MUSEUM',
  ART_GALLERY = 'ART_GALLERY',

  // RECREACIÓN
  PARK_SMALL = 'PARK_SMALL',
  PARK_LARGE = 'PARK_LARGE',
  DOG_PARK = 'DOG_PARK',
  STADIUM = 'STADIUM',
  THEME_PARK = 'THEME_PARK',
  VR_PLAZA = 'VR_PLAZA',

  // INFRAESTRUCTURA
  AIRPORT = 'AIRPORT',
  RECYCLING = 'RECYCLING',
  SUBWAY = 'SUBWAY',
  MAGLEV_STATION = 'MAGLEV_STATION',
  SPACE_PORT = 'SPACE_PORT'
}

export interface CityStats {
  money: number;
  population: number;
  jobs: number;
  happiness: number;
  health: number;
  education: number;
  crime: number;
  pollution: number;
  powerCapacity: number;
  powerUsage: number;
  waterCapacity: number;
  waterUsage: number;
  day: number;
  demandR: number;
  demandC: number;
  demandI: number;
  level: number;
}

export interface AdvisorMessage {
  text: string;
  sender: 'ADVISOR' | 'SYSTEM';
  timestamp: number;
}
